engines:
  checkstyle:
    enabled: true
    channel: "beta"
  scalastyle:
    enabled: true
    channel: "beta"
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true

ratings:
  paths:
    - "**.java"
    - "**.scala"
    - "Dockerfile"
    - "Dockerfile.test"
    - "Dockerfile.ci"

exclude_paths:
- "**/src/test/**"
