FROM benchflow/base-images:dns-java8_dev

MAINTAINER Vincenzo FERME <info@vincenzoferme.it>

ENV DOCKER_COMPOSE_VERSION 1.8.0-rc2
ENV BENCHFLOW_COMPOSE_VERSION v-dev

#Install docker-compose
RUN apk --update add curl && \
    curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

# Separate so that Docker can cache the Spark layer
# Clean up
RUN apk del --purge curl && \
    rm -rf /var/cache/apk/*

COPY configuration.yml /app/

COPY ./target/benchflow-deployment-manager.jar /app/
COPY ./services/300-deployment-manager.conf /apps/chaperone.d/300-deployment-manager.conf
 
EXPOSE 8080
